CXX = g++ -std=c++11
CXXFLAGS = -c
clean:
	rm *.o
compile_all:
	$(CXX) units/IObserver.cpp $(CXXFLAGS)
	$(CXX) units/IObservable.cpp $(CXXFLAGS)
	$(CXX) states/State.cpp $(CXXFLAGS)
	$(CXX) states/SoldierState.cpp $(CXXFLAGS)
	$(CXX) states/RogueState.cpp $(CXXFLAGS)
	$(CXX) states/BerserkerState.cpp $(CXXFLAGS)
	$(CXX) states/VampireState.cpp $(CXXFLAGS)
	$(CXX) states/WerewolfState.cpp $(CXXFLAGS)
	$(CXX) states/WolfState.cpp $(CXXFLAGS)
	$(CXX) states/MagicState.cpp $(CXXFLAGS)
	$(CXX) states/WizardState.cpp $(CXXFLAGS)
	$(CXX) states/HealerState.cpp $(CXXFLAGS)
	$(CXX) states/PriestState.cpp $(CXXFLAGS)
	$(CXX) states/WarlockState.cpp $(CXXFLAGS)
	$(CXX) states/NecromancerState.cpp $(CXXFLAGS)
	$(CXX) states/DemonState.cpp $(CXXFLAGS)
	$(CXX) units/Unit.cpp $(CXXFLAGS)
	$(CXX) units/Soldier.cpp $(CXXFLAGS)
	$(CXX) units/Rogue.cpp $(CXXFLAGS)
	$(CXX) units/Berserker.cpp $(CXXFLAGS)
	$(CXX) units/Vampire.cpp $(CXXFLAGS)
	$(CXX) units/Werewolf.cpp $(CXXFLAGS)
	$(CXX) units/Wizard.cpp $(CXXFLAGS)
	$(CXX) units/Healer.cpp $(CXXFLAGS)
	$(CXX) units/Priest.cpp $(CXXFLAGS)
	$(CXX) units/Warlock.cpp $(CXXFLAGS)
	$(CXX) units/Necromancer.cpp $(CXXFLAGS)
	$(CXX) units/SpellCaster.cpp $(CXXFLAGS)
	$(CXX) units/Demon.cpp $(CXXFLAGS)
	$(CXX) attacks/BaseAttack.cpp $(CXXFLAGS)
	$(CXX) attacks/RogueAttack.cpp $(CXXFLAGS)
	$(CXX) attacks/VampireAttack.cpp $(CXXFLAGS)
	$(CXX) attacks/WerewolfAttack.cpp $(CXXFLAGS)
	$(CXX) attacks/MagicAttack.cpp $(CXXFLAGS)
	$(CXX) spells/SpellBook.cpp $(CXXFLAGS)
	$(CXX) spells/BaseSpell.cpp $(CXXFLAGS)
	$(CXX) spells/RestoreHP.cpp $(CXXFLAGS)
	$(CXX) spells/MagicArrow.cpp $(CXXFLAGS)
	$(CXX) spells/FireBall.cpp $(CXXFLAGS)
	$(CXX) spells/SummonSpell.cpp $(CXXFLAGS)
all:compile_all
	$(CXX) run.cpp *.o && clear && ./a.out